development:
  adapter: postgresql
  database: shoe_store_development

test:
  adapter: postgresql
  database: shoe_store_test

production:
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>